"""added date tracking columns

Revision ID: ae23cc5b0bb9
Revises: a77382494e90
Create Date: 2023-11-28 01:47:06.636189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ae23cc5b0bb9"
down_revision: Union[str, None] = "a77382494e90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "post_likes",
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
    )
    op.add_column("user", sa.Column("last_login", sa.DateTime(timezone=True), nullable=True))
    op.add_column("user", sa.Column("last_request", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_request")
    op.drop_column("user", "last_login")
    op.drop_column("post_likes", "created_at")
    # ### end Alembic commands ###
